In [12]:
import itertools
from bs4 import BeautifulSoup
import requests
import pandas as pd

URL = "https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_les_plus_peupl√©es"


def get_soup_from_url(url):
    return BeautifulSoup(requests.get(url).content, 'html.parser')

In [6]:
def get_biggest_cities(limit=10):
    cities = []
    soup = get_soup_from_url(URL)
    
    # Using css nth-child selector:
    # cities_tags = soup.find('table').select('tr td:nth-child(2)')
    # cities = [city.find('a').text.strip() for city in cities_tags]
    
    rows = soup.find('table').find_all('tr')[1:]  # exclude 1st line (column names)
    for r in rows:
        cells = r.find_all('td')
        city = cells[1].find('a').text.strip()
        cities.append(city)
    return cities[:limit]

In [7]:
def get_distance_between(origin, destination):
    url = f"https://fr.distance24.org/route.json?stops={origin}|{destination}"
    data = requests.get(url).json()
    return data['distance']

In [8]:
cities = get_biggest_cities()

In [9]:
combinations = list(itertools.combinations(cities, 2))

In [10]:
distances = []
for origin, dest in combinations:
    distance = get_distance_between(origin, dest)
    distances.append(distance)

In [13]:
df = pd.DataFrame(combinations, columns=['origin', 'dest'])

In [14]:
df['distance'] = distances

In [15]:
df.sort_values('distance')

         origin         dest  distance
13    Marseille  Montpellier       126
11    Marseille         Nice       159
26     Toulouse  Montpellier       196
8         Paris        Lille       204
28     Toulouse     Bordeaux       212
20         Lyon  Montpellier       251
31         Nice  Montpellier       273
37       Nantes     Bordeaux       276
9     Marseille         Lyon       278
18         Lyon         Nice       300
10    Marseille     Toulouse       319
4         Paris       Nantes       343
17         Lyon     Toulouse       360
40  Montpellier     Bordeaux       381
21         Lyon   Strasbourg       384
1         Paris         Lyon       392
6         Paris   Strasbourg       397
43   Strasbourg        Lille       408
22         Lyon     Bordeaux       436
25     Toulouse       Nantes       466
24     Toulouse         Nice       469
7         Paris     Bordeaux       500
15    Marseille     Bordeaux       506
38       Nantes        Lille       508
19         Lyon       Nantes       516
32         Nice   Strasbourg       545
23         Lyon        Lille       558
35       Nantes  Montpellier       584
2         Paris     Toulouse       589
5         Paris  Montpellier       596
14    Marseille   Strasbourg       617
39  Montpellier   Strasbourg       629
33         Nice     Bordeaux       638
0         Paris    Marseille       661
3         Paris         Nice       688
12    Marseille       Nantes       696
44     Bordeaux        Lille       700
36       Nantes   Strasbourg       710
27     Toulouse   Strasbourg       737
42   Strasbourg     Bordeaux       760
41  Montpellier        Lille       784
29     Toulouse        Lille       792
30         Nice       Nantes       792
34         Nice        Lille       835
16    Marseille        Lille       835